### PR TITLE
Add logo and logo generating script

### PR DESCRIPTION
**Pull request by ColCarroll**
A first pass at the logo. Doesn't use PyMC3! Which is a bummer! But uses some of its colors and themes.

I generated the logo by running the script from the directory it is in. It isn't super portable, but I think this is a fine place for it to be.

pymcon_logo

### CODE REVIEW

**Review by canyon289 — APPROVED** [review]

**Comment by OriolAbril** [comment]
We should also update the metadata so the logo is shown when sharing the link in social networks!

**Comment by twiecki** [comment]
This looks great! I somehow don't like that the chains go under the font, looks a bit untidy.

**Comment by ColCarroll** [comment]
Good, actionable feedback! @OriolAbril do you know which file I'd edit for this to be a social preview?

pymcon_logo

**Comment by ColCarroll** [comment]
Ugh, got annoyed at the year being a little too low. Here's this one:
pymcon_logo

**Comment by OriolAbril** [comment]
> do you know which file I'd edit for this to be a social preview?

I have just done it, I wasn't sure it would work and wanted to try locally. I have also rebased to get the new pages (even the hidden schedule one) to use the image.

Preview of a twitter (slack, discourse, whatsapp will look somewhat similar) card with the logo:

image

**Comment by OriolAbril** [comment]
@canyon289 @ColCarroll @twiecki I will merge tomorrow if everyone if fine with it, right before merging I'd like to compress the png image to make sure card views always work and generate a favicon with it

**Comment by OriolAbril** [comment]
I will merge in a couple hours at most, then we should tweet about it to let the world know about the PyMCon logo! :tada:

**Pull request merged**
