### PR TITLE
Add initial batch of speakers

### PR DESCRIPTION
**Pull request by hectormz**
Added initial batch of speakers.

Can someone else confirm that nothing is broken? I don't think I could (ever?) get the site to deploy properly locally

### CODE REVIEW

**Comment by canyon289** [comment]
Scanning over it, it looks good. Ill try running locally to make sure nothing breaks.

We need to add the talk proposal summaries as well

**Comment by canyon289** [comment]
This is looking great!

**Comment by canyon289** [comment]
Merging, this is fantastic.

**Comment by hectormz** [comment]
Great! I hadn't add proposal summaries yet, following the keynotes pattern. We'll have both summary of talk and title?

**Comment by hectormz** [comment]
Currently doing order by alphabetical surname, can do something else like alphabetical within Advanced/Beginner etc

**Comment by canyon289** [comment]
Right now I wouldnt worry about it. I think later on we'll order by timezone and by Q&A order but for now this is great

**Pull request merged**
